### ISSUE TITLE
REQUEST-MultiworldSupport

### ISSUE THREAD

**Issue by Starflux** [HmHmmHm/automaticDoor#1]
PocketMine-MP Version: 1.6.2dev "Unleashed" (API 3.0.0-ALPHA3)
Plugin Version: 1.1-alpha
PHP version: 7.0.15

Hi thanks for a great plugin it seems to work with the default world.

the only error i get in console is:
Deprecated: Non-static method pocketmine\Server::broadcastPacket() should not be called statically in phar://C:/Users/steve/Desktop/PocketMine/plugins/phar_automaticDoor-masternew.phar/src/ifteam/automaticDoor/automaticDoor.php on line 72

If possible would you be able to update this to work in multiple worlds as defined in a config.yml as not to interfere with minigames.

I understand it has been a while since you last updated this so i understand if it is no longer supported.

Kind Regards
Star

**Comment by HmHmmHm** [comment]
Actually i don't have enough time to develop.
Because I joined the army recently.I beg your pardon. ;-;

**Comment by Starflux** [comment]
no problem, thank you for letting me know and take care.
